### ISSUE TITLE
support paging for /api/entries

### ISSUE THREAD

**Issue by clach04** [clach04/whatabagacack#2]
Handle:

* parameter page
* parameterperPage
* returning next/final `_links` in result set
* along with other result count related meta data

Sample end section:

    "_links": {
        "first": {
            "href": "https://SERVER/api/entries?sort=created&order=desc&tags=&since=0&detail=full&page=1&perPage=30"
        }, 
        "last": {
            "href": "https://SERVER/api/entries?sort=created&order=desc&tags=&since=0&detail=full&page=1&perPage=30"
        }, 
        "self": {
            "href": "https://SERVER/api/entries?sort=created&order=desc&tags=&since=0&detail=full&page=1&perPage=30"
        }
    }, 
    "limit": 30, 
    "page": 1, 
    "pages": 1, 
    "total": 6

Once done, add sanity checks for unsupported arguments and the raise an unsupported error.

For now order by id (KoReader doesn't request ordering).

**Comment by clach04** [comment]
Makes sense to work on this once https://github.com/clach04/whatabagacack/issues/6 is complete.

**Comment by SunMoon97** [comment]
@clach04 Can you assign this issue to me?

**Comment by clach04** [comment]
Hi @SunMoon97 thanks for reaching out. Paging support was added a couple of weeks ago to the https://github.com/clach04/whatabagacack/tree/paging_support branch. I **think** I'm done with (manual) testing, sadly no automated tests.

Out of curiosity do you have a use case for this project? In case the readme isn't clear this is currently very limited (and I don't plan to add authentication/authorization support).

**Comment by clach04** [comment]
See docs/notes https://github.com/clach04/whatabagacack#quick-start-server
